apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage
  labels:
    type: nfs
spec:
  storageClassName: nfs-storageclass
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteMany"]
  nfs:
    server: {NFS서버 IP}
    path: {NFS서버 저장경로} # NFS server's shared path
